// <auto-generated />
using System;
using GlobalSolution_Polaris.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace GlobalSolution_Polaris.Migrations
{
    [DbContext(typeof(MulherApiDbContext))]
    partial class MulherApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GlobalSolution_Polaris.Models.Bairro", b =>
                {
                    b.Property<int>("BairroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BairroID"), 1L, 1);

                    b.Property<int>("CidadeID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NomeBairro")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("BairroID");

                    b.HasIndex("CidadeID");

                    b.ToTable("Bairros");
                });

            modelBuilder.Entity("GlobalSolution_Polaris.Models.Cidade", b =>
                {
                    b.Property<int>("CidadeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CidadeID"), 1L, 1);

                    b.Property<int>("EstadoID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NomeCidade")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("SiglaCidade")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("CidadeID");

                    b.HasIndex("EstadoID");

                    b.ToTable("Cidades");
                });

            modelBuilder.Entity("GlobalSolution_Polaris.Models.Endereco", b =>
                {
                    b.Property<int>("EnderecoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnderecoID"), 1L, 1);

                    b.Property<int?>("BairroID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Cep")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DescricaoComplemento")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NomeRua")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("NumeroRua")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("EnderecoID");

                    b.HasIndex("BairroID");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("GlobalSolution_Polaris.Models.Estado", b =>
                {
                    b.Property<int>("EstadoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoID"), 1L, 1);

                    b.Property<string>("NomeEstado")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("SiglaEstado")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("EstadoID");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("GlobalSolution_Polaris.Models.LocalEscolhido", b =>
                {
                    b.Property<int>("LocalEscolhidoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalEscolhidoID"), 1L, 1);

                    b.Property<int>("AvaliacaoPerigo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Incidente")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("MulherID")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("LocalEscolhidoID");

                    b.HasIndex("MulherID");

                    b.ToTable("LocaisEscolhidos");
                });

            modelBuilder.Entity("GlobalSolution_Polaris.Models.Mulher", b =>
                {
                    b.Property<int>("MulherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MulherID"), 1L, 1);

                    b.Property<int>("Cpf")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("EnderecoID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Senha")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Telefone")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("MulherID");

                    b.HasIndex("EnderecoID");

                    b.ToTable("Mulheres");
                });

            modelBuilder.Entity("GlobalSolution_Polaris.Models.Bairro", b =>
                {
                    b.HasOne("GlobalSolution_Polaris.Models.Cidade", "Cidade")
                        .WithMany("Bairros")
                        .HasForeignKey("CidadeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("GlobalSolution_Polaris.Models.Cidade", b =>
                {
                    b.HasOne("GlobalSolution_Polaris.Models.Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("EstadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("GlobalSolution_Polaris.Models.Endereco", b =>
                {
                    b.HasOne("GlobalSolution_Polaris.Models.Bairro", null)
                        .WithMany("Enderecos")
                        .HasForeignKey("BairroID");
                });

            modelBuilder.Entity("GlobalSolution_Polaris.Models.LocalEscolhido", b =>
                {
                    b.HasOne("GlobalSolution_Polaris.Models.Mulher", "mulher")
                        .WithMany()
                        .HasForeignKey("MulherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mulher");
                });

            modelBuilder.Entity("GlobalSolution_Polaris.Models.Mulher", b =>
                {
                    b.HasOne("GlobalSolution_Polaris.Models.Endereco", "Endereco")
                        .WithMany("MulheresRel")
                        .HasForeignKey("EnderecoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("GlobalSolution_Polaris.Models.Bairro", b =>
                {
                    b.Navigation("Enderecos");
                });

            modelBuilder.Entity("GlobalSolution_Polaris.Models.Cidade", b =>
                {
                    b.Navigation("Bairros");
                });

            modelBuilder.Entity("GlobalSolution_Polaris.Models.Endereco", b =>
                {
                    b.Navigation("MulheresRel");
                });

            modelBuilder.Entity("GlobalSolution_Polaris.Models.Estado", b =>
                {
                    b.Navigation("Cidades");
                });
#pragma warning restore 612, 618
        }
    }
}
